### PR TITLE
Add unicycler

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by ODiogoSilva** [comment]
Ah, could you just update the changelog.md with the new component?

**Comment by jacarrico** [comment]
Just a note: Unicycler uses several modules such as spades correct? 
Ideally, Unicycler should be also be broken down in components and be represented as a FlowCraft recipe . Am I correct ?

**Comment by sjackman** [comment]
> Just a note: Unicycler uses several modules such as spades correct?

Correct. The stages for short-read assembly are…

1. Correct reads with SPAdes
2. Assemble reads with SPAdes at multiple values of *k*
3. Estimate copy number of unitigs
4. Clean the assembly graph
5. Apply SPAdes repeat resolution
6. Polish the assembly with Pilon
7. Rotate circular contigs to the starting gene `dnaA` or `repA`

> Ideally, Unicycler should be also be broken down in components and be represented as a FlowCraft recipe . Am I correct ?

Yep! The plan is to separate it out into the components that are separable. It's now really designed to be split up, but some steps could be extract. Read correction and polishing for example would be easy to extract.

**Comment by sjackman** [comment]
Unicycler has the options `--no_correct`, `--no_rotate`, and `--no_pilon`.

**Comment by sjackman** [comment]
I've added `--no_correct` and `--no_pilon` to the default options.

**Comment by sjackman** [comment]
> Ah, could you just update the changelog.md with the new component?

Done. Good to go?

**Comment by sjackman** [comment]
Thanks for merging!

**Pull request merged**
